/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ParameterPollution;

import java.util.ArrayList;
import static spark.Spark.*;

public class App {

    public static void main(String[] args) {

        // GOTO: http://localhost:4567
        //GET TESTING
        ArrayList<String> instances = new ArrayList<>();
        String formBody = "<form action=\"/postTester\" method=\"post\">"
                + "<label>Username</label><br>"
                + "<input class=\"registration\" type=\"text\" name=\"username\" placeholder=\"Required\"><br>"
                + "<label>Password</label><br>"
                + "<input class=\"registration\" type=\"password\" name=\"password\" placeholder=\"Required\"><br>"
                + "<input type=\"submit\" value=\"Login\">"
                + "</form>";

        get("/", (request, response) -> "<html><body><h1>HTTP Paramater Pollution GET Testing</h1>"
                + "<ul>"
                + "<li><a href=\"/getTester\">GET Tester</a></li>"
                + "<li><a href=\"/postTester\">POST Tester</a></li>"
                + "</ul>"
                + "</body></html>");

        get("/getTester", (request, response) -> {
            String username = request.queryParams("username");
            String password = request.queryParams("password");
            String getInstance
                    = "<h2>GET Instance</h2>"
                    + "<ul>"
                    + "<li>Username: " + username + "</li>"
                    + "<li>Password: " + password + "</li>"
                    + "</ul>";
            if (username != null && password != null) {
                instances.add(getInstance);
            }
            String bulkReturn = "";
            for (String instance : instances) {
                bulkReturn = bulkReturn + instance;
            }
            if (bulkReturn.equals("")) {
                bulkReturn = "To test get parameters append ?username=Test&"
                        + "password=TestPass to the address striing and hit enter.";
            }
            return "<html><body><h1>HTTP Paramater Pollution GET Testing</h1>"
                    + bulkReturn
                    + "<br><a href=\"/\">Return HOME</a></body></html>";
        });

        //POST TESTING
        get("/postTester", (request, response)
                -> "<html><body><h1>HTTP Paramater Pollution POST Testing</h1>"
                + formBody
                + "<br><a href=\"/\">Return HOME</a></body></html>"
        );

        post("/postTester", (request, response) -> {
            String username = request.queryParams("username");
            String password = request.queryParams("password");
            String getInstance
                    = "<h2>POST Instance</h2>"
                    + "<ul>"
                    + "<li>Username: " + username + "</li>"
                    + "<li>Password: " + password + "</li>"
                    + "</ul>";
            instances.add(getInstance);
            String bulkReturn = "";
            for (String instance : instances) {
                bulkReturn = bulkReturn + instance;
            }
            return "<html><body><h1>HTTP Paramater Pollution POST Testing</h1>"
                    + formBody
                    + bulkReturn
                    + "<br><a href=\"/\">Return HOME</a></body></html>";
        });
    }

}
